/*
 * udk_types.h
 *
 * Created: 12/11/2014 12:45:27 PM
 *  Author: Levi.Balling
 */ 


#ifndef UDK_TYPES_H_
#define UDK_TYPES_H_


#include "compiler.h"
#include "system_sam4e.h"
#include "exceptions.h"

//here we will keep all of the defines that determine what the pins do. similar to the sam4e_ek.h file does.

//INPUTS
//KEY Input 0
#define PIN_KEY_IN_0  	{PIO_PD19, PIOD, ID_PIOD, PIO_INPUT, PIO_PULLUP | PIO_DEBOUNCE }
#define GPIO_KEY_IN_0       (PIO_PD19_IDX)
#define GPIO_KEY_IN_0_FLAGS (IOPORT_MODE_PULLDOWN | IOPORT_MODE_DEBOUNCE)
//#define GPIO_PUSH_BUTTON_1_SENSE (IOPORT_SENSE_RISING)

#define PIN_KEY_IN_0_MASK  PIO_PD19
#define PIN_KEY_IN_0_PIO   PIOD
#define PIN_KEY_IN_0_ID    ID_PIOD
#define PIN_KEY_IN_0_TYPE  PIO_INPUT
#define PIN_KEY_IN_0_ATTR  (PIO_PULLUP | PIO_DEBOUNCE )//| PIO_IT_RISE_EDGE)
//#define PIN_KEY_IN_0_IRQn  PIOA_IRQn

//KEY INPUT 1
#define PIN_KEY_IN_1  	{PIO_PD20, PIOD, ID_PIOD, PIO_INPUT, PIO_PULLUP | PIO_DEBOUNCE }
#define GPIO_KEY_IN_1       (PIO_PD20_IDX)
#define GPIO_KEY_IN_1_FLAGS (IOPORT_MODE_PULLDOWN | IOPORT_MODE_DEBOUNCE)
//#define GPIO_PUSH_BUTTON_1_SENSE (IOPORT_SENSE_RISING)

#define PIN_KEY_IN_1_MASK  PIO_PD20
#define PIN_KEY_IN_1_PIO   PIOD
#define PIN_KEY_IN_1_ID    ID_PIOD
#define PIN_KEY_IN_1_TYPE  PIO_INPUT
#define PIN_KEY_IN_1_ATTR  (PIO_PULLUP | PIO_DEBOUNCE )//| PIO_IT_RISE_EDGE)
//#define PIN_KEY_IN_1_IRQn  PIOA_IRQn

//KEY INPUT 2
#define PIN_KEY_IN_2  	{PIO_PD21, PIOD, ID_PIOD, PIO_INPUT, PIO_PULLUP | PIO_DEBOUNCE }
#define GPIO_KEY_IN_2       (PIO_PD21_IDX)
#define GPIO_KEY_IN_2_FLAGS (IOPORT_MODE_PULLDOWN | IOPORT_MODE_DEBOUNCE)
//#define GPIO_PUSH_BUTTON_1_SENSE (IOPORT_SENSE_RISING)

#define PIN_KEY_IN_2_MASK  PIO_PD21
#define PIN_KEY_IN_2_PIO   PIOD
#define PIN_KEY_IN_2_ID    ID_PIOD
#define PIN_KEY_IN_2_TYPE  PIO_INPUT
#define PIN_KEY_IN_2_ATTR  (PIO_PULLUP | PIO_DEBOUNCE )//| PIO_IT_RISE_EDGE)
//#define PIN_KEY_IN_2_IRQn  PIOA_IRQn

//KEY INPUT 3
#define PIN_KEY_IN_3  	{PIO_PD22, PIOD, ID_PIOD, PIO_INPUT, PIO_PULLUP | PIO_DEBOUNCE }
#define GPIO_KEY_IN_3       (PIO_PD22_IDX)
#define GPIO_KEY_IN_3_FLAGS (IOPORT_MODE_PULLDOWN | IOPORT_MODE_DEBOUNCE)
//#define GPIO_PUSH_BUTTON_1_SENSE (IOPORT_SENSE_RISING)

#define PIN_KEY_IN_3_MASK  PIO_PD22
#define PIN_KEY_IN_3_PIO   PIOD
#define PIN_KEY_IN_3_ID    ID_PIOD
#define PIN_KEY_IN_3_TYPE  PIO_INPUT
#define PIN_KEY_IN_3_ATTR  (PIO_PULLUP | PIO_DEBOUNCE )//| PIO_IT_RISE_EDGE)
//#define PIN_KEY_IN_3_IRQn  PIOA_IRQn

//KEY INPUT 4
#define PIN_KEY_IN_4  	{PIO_PD23, PIOD, ID_PIOD, PIO_INPUT, PIO_PULLUP | PIO_DEBOUNCE }
#define GPIO_KEY_IN_4       (PIO_PD23_IDX)
#define GPIO_KEY_IN_4_FLAGS (IOPORT_MODE_PULLDOWN | IOPORT_MODE_DEBOUNCE)
//#define GPIO_PUSH_BUTTON_1_SENSE (IOPORT_SENSE_RISING)

#define PIN_KEY_IN_4_MASK  PIO_PD23
#define PIN_KEY_IN_4_PIO   PIOD
#define PIN_KEY_IN_4_ID    ID_PIOD
#define PIN_KEY_IN_4_TYPE  PIO_INPUT
#define PIN_KEY_IN_4_ATTR  (PIO_PULLUP | PIO_DEBOUNCE )//| PIO_IT_RISE_EDGE)
//#define PIN_KEY_IN_4_IRQn  PIOA_IRQn

//KEY INPUT 5
#define PIN_KEY_IN_5  	{PIO_PD24, PIOD, ID_PIOD, PIO_INPUT, PIO_PULLUP | PIO_DEBOUNCE }
#define GPIO_KEY_IN_5       (PIO_PD24_IDX)
#define GPIO_KEY_IN_5_FLAGS (IOPORT_MODE_PULLDOWN | IOPORT_MODE_DEBOUNCE)
//#define GPIO_PUSH_BUTTON_1_SENSE (IOPORT_SENSE_RISING)

#define PIN_KEY_IN_5_MASK  PIO_PD24
#define PIN_KEY_IN_5_PIO   PIOD
#define PIN_KEY_IN_5_ID    ID_PIOD
#define PIN_KEY_IN_5_TYPE  PIO_INPUT
#define PIN_KEY_IN_5_ATTR  (PIO_PULLUP | PIO_DEBOUNCE )//| PIO_IT_RISE_EDGE)
//#define PIN_KEY_IN_5_IRQn  PIOA_IRQn

//KEY INPUT 6
#define PIN_KEY_IN_6  	{PIO_PD25, PIOD, ID_PIOD, PIO_INPUT, PIO_PULLUP | PIO_DEBOUNCE }
#define GPIO_KEY_IN_6       (PIO_PD25_IDX)
#define GPIO_KEY_IN_6_FLAGS (IOPORT_MODE_PULLDOWN | IOPORT_MODE_DEBOUNCE)
//#define GPIO_PUSH_BUTTON_1_SENSE (IOPORT_SENSE_RISING)

#define PIN_KEY_IN_6_MASK  PIO_PD25
#define PIN_KEY_IN_6_PIO   PIOD
#define PIN_KEY_IN_6_ID    ID_PIOD
#define PIN_KEY_IN_6_TYPE  PIO_INPUT
#define PIN_KEY_IN_6_ATTR  (PIO_PULLUP | PIO_DEBOUNCE )//| PIO_IT_RISE_EDGE)
//#define PIN_KEY_IN_6_IRQn  PIOA_IRQn

//KEY INPUT 7
#define PIN_KEY_IN_7  	{PIO_PD26, PIOD, ID_PIOD, PIO_INPUT, PIO_PULLUP | PIO_DEBOUNCE }
#define GPIO_KEY_IN_7       (PIO_PD26_IDX)
#define GPIO_KEY_IN_7_FLAGS (IOPORT_MODE_PULLDOWN | IOPORT_MODE_DEBOUNCE)
//#define GPIO_PUSH_BUTTON_1_SENSE (IOPORT_SENSE_RISING)

#define PIN_KEY_IN_7_MASK  PIO_PD26
#define PIN_KEY_IN_7_PIO   PIOD
#define PIN_KEY_IN_7_ID    ID_PIOD
#define PIN_KEY_IN_7_TYPE  PIO_INPUT
#define PIN_KEY_IN_7_ATTR  (PIO_PULLUP | PIO_DEBOUNCE )//| PIO_IT_RISE_EDGE)
//#define PIN_KEY_IN_7_IRQn  PIOA_IRQn

//KEY INPUT 8
#define PIN_KEY_IN_8  	{PIO_PD27, PIOD, ID_PIOD, PIO_INPUT, PIO_PULLUP | PIO_DEBOUNCE }
#define GPIO_KEY_IN_8       (PIO_PD27_IDX)
#define GPIO_KEY_IN_8_FLAGS (IOPORT_MODE_PULLDOWN | IOPORT_MODE_DEBOUNCE)
//#define GPIO_PUSH_BUTTON_1_SENSE (IOPORT_SENSE_RISING)

#define PIN_KEY_IN_8_MASK  PIO_PD27
#define PIN_KEY_IN_8_PIO   PIOD
#define PIN_KEY_IN_8_ID    ID_PIOD
#define PIN_KEY_IN_8_TYPE  PIO_INPUT
#define PIN_KEY_IN_8_ATTR  (PIO_PULLUP | PIO_DEBOUNCE )//| PIO_IT_RISE_EDGE)
//#define PIN_KEY_IN_8_IRQn  PIOA_IRQn

//KEY INPUT 9
#define PIN_KEY_IN_9  	{PIO_PD28, PIOD, ID_PIOD, PIO_INPUT, PIO_PULLUP | PIO_DEBOUNCE }
#define GPIO_KEY_IN_9       (PIO_PD28_IDX)
#define GPIO_KEY_IN_9_FLAGS (IOPORT_MODE_PULLDOWN | IOPORT_MODE_DEBOUNCE)
//#define GPIO_PUSH_BUTTON_1_SENSE (IOPORT_SENSE_RISING)

#define PIN_KEY_IN_9_MASK  PIO_PD28
#define PIN_KEY_IN_9_PIO   PIOD
#define PIN_KEY_IN_9_ID    ID_PIOD
#define PIN_KEY_IN_9_TYPE  PIO_INPUT
#define PIN_KEY_IN_9_ATTR  (PIO_PULLUP | PIO_DEBOUNCE )//| PIO_IT_RISE_EDGE)
//#define PIN_KEY_IN_9_IRQn  PIOA_IRQn

//KEY INPUT 10
#define PIN_KEY_IN_10  	{PIO_PD29, PIOD, ID_PIOD, PIO_INPUT, PIO_PULLUP | PIO_DEBOUNCE }
#define GPIO_KEY_IN_10       (PIO_PD29_IDX)
#define GPIO_KEY_IN_10_FLAGS (IOPORT_MODE_PULLDOWN | IOPORT_MODE_DEBOUNCE)
//#define GPIO_PUSH_BUTTON_1_SENSE (IOPORT_SENSE_RISING)

#define PIN_KEY_IN_10_MASK  PIO_PD29
#define PIN_KEY_IN_10_PIO   PIOD
#define PIN_KEY_IN_10_ID    ID_PIOD
#define PIN_KEY_IN_10_TYPE  PIO_INPUT
#define PIN_KEY_IN_10_ATTR  (PIO_PULLUP | PIO_DEBOUNCE )//| PIO_IT_RISE_EDGE)
//#define PIN_KEY_IN_10_IRQn  PIOA_IRQn




//OUTPUTS

//Backlight OUTPUT 
#define PIN_BACKLIGHT_OUT 	{PIO_PA0, PIOA, ID_PIOA, PIO_OUTPUT_0, PIO_DEFAULT}
#define PIN_BACKLIGHT_OUT_MASK  PIO_PA0
#define PIN_BACKLIGHT_OUT_PIO   PIOA
#define PIN_BACKLIGHT_OUT_ID    ID_PIOA
#define PIN_BACKLIGHT_OUT_TYPE  PIO_OUTPUT_0
#define PIN_BACKLIGHT_OUT_ATTR  PIO_DEFAULT

#define GPIO_BACKLIGHT_OUT       (PIO_PA0_IDX)
#define GPIO_BACKLIGHT_OUT_FLAGS (0)
#define GPIO_BACKLIGHT_OUT_ACTIVE_LEVEL    IOPORT_PIN_LEVEL_LOW
#define GPIO_BACKLIGHT_OUT_INACTIVE_LEVEL  IOPORT_PIN_LEVEL_HIGH

//KEY OUTPUT 0
#define PIN_KEY_OUT_0 	{PIO_PA1, PIOA, ID_PIOA, PIO_OUTPUT_1, PIO_DEFAULT}
#define PIN_KEY_OUT_0_MASK  PIO_PA1
#define PIN_KEY_OUT_0_PIO   PIOA
#define PIN_KEY_OUT_0_ID    ID_PIOA
#define PIN_KEY_OUT_0_TYPE  PIO_OUTPUT_1
#define PIN_KEY_OUT_0_ATTR  PIO_DEFAULT

#define GPIO_KEY_OUT_0       (PIO_PA1_IDX)
#define GPIO_KEY_OUT_0_FLAGS (0)
#define GPIO_KEY_OUT_0_ACTIVE_LEVEL    IOPORT_PIN_LEVEL_LOW
#define GPIO_KEY_OUT_0_INACTIVE_LEVEL  IOPORT_PIN_LEVEL_HIGH

//KEY OUTPUT 1
#define PIN_KEY_OUT_1 	{PIO_PA2, PIOA, ID_PIOA, PIO_OUTPUT_1, PIO_DEFAULT}
#define PIN_KEY_OUT_1_MASK  PIO_PA2
#define PIN_KEY_OUT_1_PIO   PIOA
#define PIN_KEY_OUT_1_ID    ID_PIOA
#define PIN_KEY_OUT_1_TYPE  PIO_OUTPUT_1
#define PIN_KEY_OUT_1_ATTR  PIO_DEFAULT

#define GPIO_KEY_OUT_1       (PIO_PA2_IDX)
#define GPIO_KEY_OUT_1_FLAGS (0)
#define GPIO_KEY_OUT_1_ACTIVE_LEVEL    IOPORT_PIN_LEVEL_LOW
#define GPIO_KEY_OUT_1_INACTIVE_LEVEL  IOPORT_PIN_LEVEL_HIGH

//KEY OUTPUT 2
#define PIN_KEY_OUT_2 	{PIO_PA3, PIOA, ID_PIOA, PIO_OUTPUT_1, PIO_DEFAULT}
#define PIN_KEY_OUT_2_MASK  PIO_PA3
#define PIN_KEY_OUT_2_PIO   PIOA
#define PIN_KEY_OUT_2_ID    ID_PIOA
#define PIN_KEY_OUT_2_TYPE  PIO_OUTPUT_1
#define PIN_KEY_OUT_2_ATTR  PIO_DEFAULT

#define GPIO_KEY_OUT_2       (PIO_PA3_IDX)
#define GPIO_KEY_OUT_2_FLAGS (0)
#define GPIO_KEY_OUT_2_ACTIVE_LEVEL    IOPORT_PIN_LEVEL_LOW
#define GPIO_KEY_OUT_2_INACTIVE_LEVEL  IOPORT_PIN_LEVEL_HIGH

//KEY OUTPUT 3
#define PIN_KEY_OUT_3 	{PIO_PA4, PIOA, ID_PIOA, PIO_OUTPUT_1, PIO_DEFAULT}
#define PIN_KEY_OUT_3_MASK  PIO_PA4
#define PIN_KEY_OUT_3_PIO   PIOA
#define PIN_KEY_OUT_3_ID    ID_PIOA
#define PIN_KEY_OUT_3_TYPE  PIO_OUTPUT_1
#define PIN_KEY_OUT_3_ATTR  PIO_DEFAULT

#define GPIO_KEY_OUT_3       (PIO_PA4_IDX)
#define GPIO_KEY_OUT_3_FLAGS (0)
#define GPIO_KEY_OUT_3_ACTIVE_LEVEL    IOPORT_PIN_LEVEL_LOW
#define GPIO_KEY_OUT_3_INACTIVE_LEVEL  IOPORT_PIN_LEVEL_HIGH

//KEY OUTPUT 4
#define PIN_KEY_OUT_4 	{PIO_PA5, PIOA, ID_PIOA, PIO_OUTPUT_1, PIO_DEFAULT}
#define PIN_KEY_OUT_4_MASK  PIO_PA5
#define PIN_KEY_OUT_4_PIO   PIOA
#define PIN_KEY_OUT_4_ID    ID_PIOA
#define PIN_KEY_OUT_4_TYPE  PIO_OUTPUT_1
#define PIN_KEY_OUT_4_ATTR  PIO_DEFAULT

#define GPIO_KEY_OUT_4       (PIO_PA5_IDX)
#define GPIO_KEY_OUT_4_FLAGS (0)
#define GPIO_KEY_OUT_4_ACTIVE_LEVEL    IOPORT_PIN_LEVEL_LOW
#define GPIO_KEY_OUT_4_INACTIVE_LEVEL  IOPORT_PIN_LEVEL_HIGH

//KEY OUTPUT 5
#define PIN_KEY_OUT_5 	{PIO_PA6, PIOA, ID_PIOA, PIO_OUTPUT_1, PIO_DEFAULT}
#define PIN_KEY_OUT_5_MASK  PIO_PA6
#define PIN_KEY_OUT_5_PIO   PIOA
#define PIN_KEY_OUT_5_ID    ID_PIOA
#define PIN_KEY_OUT_5_TYPE  PIO_OUTPUT_1
#define PIN_KEY_OUT_5_ATTR  PIO_DEFAULT

#define GPIO_KEY_OUT_5       (PIO_PA6_IDX)
#define GPIO_KEY_OUT_5_FLAGS (0)
#define GPIO_KEY_OUT_5_ACTIVE_LEVEL    IOPORT_PIN_LEVEL_LOW
#define GPIO_KEY_OUT_5_INACTIVE_LEVEL  IOPORT_PIN_LEVEL_HIGH

//KEY OUTPUT 6
#define PIN_KEY_OUT_6 	{PIO_PA9, PIOA, ID_PIOA, PIO_OUTPUT_1, PIO_DEFAULT}
#define PIN_KEY_OUT_6_MASK  PIO_PA9
#define PIN_KEY_OUT_6_PIO   PIOA
#define PIN_KEY_OUT_6_ID    ID_PIOA
#define PIN_KEY_OUT_6_TYPE  PIO_OUTPUT_1
#define PIN_KEY_OUT_6_ATTR  PIO_DEFAULT

#define GPIO_KEY_OUT_6       (PIO_PA9_IDX)
#define GPIO_KEY_OUT_6_FLAGS (0)
#define GPIO_KEY_OUT_6_ACTIVE_LEVEL    IOPORT_PIN_LEVEL_LOW
#define GPIO_KEY_OUT_6_INACTIVE_LEVEL  IOPORT_PIN_LEVEL_HIGH

//KEY OUTPUT 7
#define PIN_KEY_OUT_7 	{PIO_PA10, PIOA, ID_PIOA, PIO_OUTPUT_1, PIO_DEFAULT}
#define PIN_KEY_OUT_7_MASK  PIO_PA10
#define PIN_KEY_OUT_7_PIO   PIOA
#define PIN_KEY_OUT_7_ID    ID_PIOA
#define PIN_KEY_OUT_7_TYPE  PIO_OUTPUT_1
#define PIN_KEY_OUT_7_ATTR  PIO_DEFAULT

#define GPIO_KEY_OUT_7       (PIO_PA10_IDX)
#define GPIO_KEY_OUT_7_FLAGS (0)
#define GPIO_KEY_OUT_7_ACTIVE_LEVEL    IOPORT_PIN_LEVEL_LOW
#define GPIO_KEY_OUT_7_INACTIVE_LEVEL  IOPORT_PIN_LEVEL_HIGH

//KEY OUTPUT 8
#define PIN_KEY_OUT_8 	{PIO_PA11, PIOA, ID_PIOA, PIO_OUTPUT_1, PIO_DEFAULT}
#define PIN_KEY_OUT_8_MASK  PIO_PA11
#define PIN_KEY_OUT_8_PIO   PIOA
#define PIN_KEY_OUT_8_ID    ID_PIOA
#define PIN_KEY_OUT_8_TYPE  PIO_OUTPUT_1
#define PIN_KEY_OUT_8_ATTR  PIO_DEFAULT

#define GPIO_KEY_OUT_8       (PIO_PA11_IDX)
#define GPIO_KEY_OUT_8_FLAGS (0)
#define GPIO_KEY_OUT_8_ACTIVE_LEVEL    IOPORT_PIN_LEVEL_LOW
#define GPIO_KEY_OUT_8_INACTIVE_LEVEL  IOPORT_PIN_LEVEL_HIGH




//#define LED_0_NAME      "Blue LED D2"
//#define PIN_LED_0       {PIO_PA0, PIOA, ID_PIOA, PIO_OUTPUT_1, PIO_DEFAULT}
//#define PIN_LED_0_MASK  PIO_PA1
//#define PIN_LED_0_PIO   PIOA
//#define PIN_LED_0_ID    ID_PIOA
//#define PIN_LED_0_TYPE  PIO_OUTPUT_1
//#define PIN_LED_0_ATTR  PIO_DEFAULT
//
//#define LED0_GPIO            (PIO_PA0_IDX)
//#define LED0_FLAGS           (0)
//#define LED0_ACTIVE_LEVEL    IOPORT_PIN_LEVEL_LOW
//#define LED0_INACTIVE_LEVEL  IOPORT_PIN_LEVEL_HIGH




#endif /* UDK_TYPES_H_ */
